### ISSUE TITLE
Should eslint-plugin-proper-arrows work with NOOP or empty function ?

### ISSUE THREAD

**Issue by matthewharwood** [getify/eslint-plugin-proper-arrows#2]
Should`eslint-plugin-proper-arrows` work with NOOP ?

const NOOP = () => {};

**Comment by getify** [comment]
I think it's certainly reasonable to consider an exception flag to ignore these... but we need to explore a few bits first.

1. Which of the 3 (or all 3?) current rules do you think this should apply to? Seems like probably `"this"` for sure, but what about that rule's `"no-global"` mode? And what about the `"name"` rule? Need to clearly spell out and justify each exception so we don't go overly broad with it.

2. Should we expand this exception to include any "simple" or "trivial" arrows instead of only no-ops? Like `x => x` (identity function), `() => y` (closure function), and `x => 1` (constant function)? If so, what heuristic would we use for these simple/trivial arrows? Maybe:

   - only 0-1 parameters
   - only a single return expression (literal or identifier only) or an empty body `{}`

Thoughts?

**Comment by getify** [comment]
I think we'll just add an "ignore-trivial" exception flag to all rules ("name", "this", "params", and "return").

Trivial will be defined as: 0-1 params (only identifier), returns no value (`{}`) or any single value (primitive literal or variable) as concise expression.

**Comment by matthewharwood** [comment]
I like "ignore-trivial". I think your rule-set defining of "trivial" will work well too.
